# Generated by Django 5.1 on 2024-09-05 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="board",
            name="content",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        10, "최소 10글자 이상은 입력하여 주셔야합니다."
                    )
                ],
                verbose_name="내용",
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="nickname",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, "닉네임을 입력하셔야합니다."
                    )
                ],
                verbose_name="닉네임",
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        3, "최소 세 글자 이상은 입력해주셔야 합니다."
                    )
                ],
                verbose_name="제목",
            ),
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(fields=["title"], name="board_title_idx"),
        ),
    ]
